name: 'build docker'
description: 'Generate a lightweight docker image.'
runs:
  using: 'composite'
  steps:
    -
      name: pwd
      run: bash
      shell: bash
    -
      name: builder
      run: ./.github/actions/builder/builder.sh
      shell: bash
