version: "3.9"

services:
  runner:
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: https://github.com/ykawa/test
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      RUNNER_WORKDIR: /tmp/runner/work
      LABELS: linux,x64
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/tmp/runner:/tmp/runner'
