name: release my tiny debian.
on:
  push:
    branches: [ main ]
      #    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        archtec: [amd64, arm64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: build small docker image
        uses: ./.github/actions/builder

          #      - name: Log into registry ${{ env.REGISTRY }}
          #        if: github.event_name != 'pull_request'
          #          registry: ${{ env.REGISTRY }}
          #          username: ${{ github.actor }}
          #          password: ${{ secrets.GITHUB_TOKEN }}
          #
          #      - name: Extract Docker metadata
          #        id: meta
          #        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          #        with:
          #          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          #
          #      - name: Build and push Docker image
          #        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          #        with:
          #          context: .
          #          push: ${{ github.event_name != 'pull_request' }}
          #          tags: ${{ steps.meta.outputs.tags }}
          #          labels: ${{ steps.meta.outputs.labels }}
          #
